version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 2170721
      MYSQL_DATABASE: estudiantessql
      MYSQL_USER: Brauny
      MYSQL_PASSWORD: 2170721